### PR TITLE
issue: 91 right align the budget-tree-map and sort it alphabetically

### LINKED ISSUE #91: budget-tree-map: Right align table and sort alphabetically
table_sort

Need to sort this list alphabetically.
Also change alignment to right align?

### PR DESCRIPTION
**Pull request by dashcraft**
Changed the CSS to right align the table header and table data cells. Added some margin for readability, expanded the table for visual consistency when right aligned.

Changed the sort on the data from being the expense column greatest to least amount, to alphabetically via the item column.

resolve #91

### CODE REVIEW

**Comment by smurphy8** [comment]
Could you throw in a screen shot please?

**Comment by dashcraft** [comment]
Sorry about that, i had posted the images on the slack channel...

The first image is the right aligned table (and headers)
the second image is right aligned and alphabetically organized as opposed to 
ordered by decreasing budget $$.

right_align_budget
right_align_sorted_budget

**Comment by smurphy8** [comment]
Hmm, I pulled your commit and ran it but the alignment looked different for me.  I tried it in Chrome version 55.0.2883.87 (64-bit)
And firefox 51.0a2 (2016-10-17) (64-bit)

I also tried it in responsive mode which did look great!

What browser is that screen shot from?
Here is what I saw:
tablealignmentproblem

**Comment by dashcraft** [comment]
firefox, let me check it for compatability across browsers real quick and also across a wide screen, my screen i tested on was only 1094px , i guess i could've done that before pushing! :)

**Comment by dashcraft** [comment]
There, the issue was that the data table isn't reposive above 1140px, so i had to set a max width for the table to 1140px. Tested on firefox and latest chrome, no issues.

Let me know if there is anything else!

**Review by smurphy8 — APPROVED** [review]
:shipit:

**Comment by mkchandler** [comment]
@dashcraft @smurphy8 My only concern about this change was that I think only the number values were supposed to be right aligned.

**Comment by smurphy8** [comment]
That makes sense ...

**Pull request merged**
