### PR TITLE
Setup Travis CI

### PR DESCRIPTION
**Pull request by makenova**
use virtual screen for browser tests
run tests once and use chromium instead of chrome for Travis CI

### CODE REVIEW

**Comment by makenova** [comment]
There were some errors in the CI with the submoudules so I told Travis to ignore it.

Also, Chrome isn't available in the container where the tests are run so we have to use Chromium. 

If you're interested, I found the details for the chromium fix [here](https://github.com/MrOrz/SeeSS/blob/master/test/karma.conf.js#L98), via [this](https://github.com/karma-runner/karma/issues/1144#issuecomment-53633076) issue.

**Comment by smurphy8** [comment]
Awesome,  is there a link to the CI in action somewhere?

**Comment by makenova** [comment]
Yup. Right [here](https://travis-ci.org/codeforokc/openbudgetokc).

I can also add the badge to the Readme file.

**Comment by smurphy8** [comment]
That would be cool, thanks!

**Comment by makenova** [comment]
There isn't actually a build for the master branch yet, so I think the badge is going to remain status unknown until this branch is merged.

**Comment by smurphy8** [comment]
K

**Review by mkchandler — APPROVED** [review]
This all looks great!

**Pull request merged**
