### PR TITLE
created spaces around "Code for OKC" in footer of page.

### PR DESCRIPTION
**Pull request by mathewmorris**
Small visual tweak if wanted.

### CODE REVIEW

**Comment by mkchandler** [comment]
@mathewmorris Can you do the same before/after screen shots on this one? Thanks so much for tackling these changes!!

**Comment by mathewmorris** [comment]
Yeah! No problem! Just a minute 👍

**Comment by mathewmorris** [comment]
Before:
image
After:
image

**Review by mkchandler — APPROVED** [review]
Looks good 👍

**Pull request merged**
