### PR TITLE
Dev radar iss num 42

### PR DESCRIPTION
**Pull request by smurphy8**
:no_good:   For #42 
The code isn't ready but I like making pull requests early so other people can see where things are heading and make comments if desired.

Just let me know if you all hate this habit and I will stop!
:warning: :warning:

### CODE REVIEW

**Comment by smurphy8** [comment]
As of 2016_07_14, this is what you should see for the radar chart. 
I used a thresholding function to exclude all items under 7% (because that looked nice)

radar_example_2016_07_14

**Comment by smurphy8** [comment]
Okay I cleaned this up quite a bit. 
But it could definitely use some more love but gets the main point across.  

I think it is in good enough shape to push it in and then start multiple issues to fix parts of it as needed.  

radar_screen

**Comment by railsnewbie257** [comment]
Good stuff! A lot going on here, might be nice to squash your commits.

**Comment by smurphy8** [comment]
Can do

**Comment by smurphy8** [comment]
@railsnewbie257 Little better?

**Comment by smurphy8** [comment]
@mkchandler @cahiller  any luck getting another data set?

**Comment by cahiller** [comment]
hey @smurphy8 I haven't gotten 2017 data, but I'm thinking of asking for previous years too. Maybe Doug can get that to us faster than the 2017 data? Would you be interested in being able to see past years?

**Comment by cahiller** [comment]
Looks good. Do you want to make any more changes before I merge it @smurphy8 ?

**Comment by smurphy8** [comment]
@cahiller you might as well wait, I am looking over the data in the sandbox and I am going to have to make significant changes to get it to conform to that csv.  

Not a problem, just some time.  

On the older data, please do request!  Thank you.

**Comment by cahiller** [comment]
ok sounds good!

**Comment by cahiller** [comment]
[CODE for OKC FY17 Budget.xlsx](https://github.com/codeforokc/openbudgetokc/files/398442/CODE.for.OKC.FY17.Budget.xlsx)

2017 budget data is attached so we can compare 2016 to 2017

**Comment by smurphy8** [comment]
screenshot from 2016-08-10 20 13 59

New data is working! Getting close

**Comment by smurphy8** [comment]
@cahiller  I think after https://github.com/codeforokc/openbudgetokc/pull/51 this can be merged in.  The multi axis still needs work but I think it should be broken up into more issues.

**Comment by cahiller** [comment]
2017 data is merged in! Take a look and see what you think

**Comment by smurphy8** [comment]
@cahiller  Data worked great, I made the json and added it to the radar.  
Just built a legend for the radar as well.  

Probably a good point to merge in and then make issues for all the remaining work with the radar.

**Pull request merged**
