### PR TITLE
#71 #67 Added Descriptions and changed 'fy' to 'FY'.

### PR DESCRIPTION
**Pull request by mathewmorris**
# #71 - Added description and changed 'fy' to 'FY'.

## Before
image

## After
image

# #67 Added description. Had to bump margins around so everything still looked good.

## Before
image

## After
image

### CODE REVIEW

**Comment by mathewmorris** [comment]
Added another commit. Found a space needed in "monthlymeetups"

## Before 
image

## After 
image

**Comment by mkchandler** [comment]
@mathewmorris One thing I think that would be good for consistency is to break out the title and description from the tree map visualization, instead putting it in the body of the page like the Budget Evolution page. Does that make sense?

**Comment by mathewmorris** [comment]
Totally. I agree. Ill work on it 👌🏻

**Comment by mathewmorris** [comment]
## Before
image

## After
image

**Review by mkchandler — APPROVED** [review]

**Pull request merged**
