### PR TITLE
Deprecate sandbox

### PR DESCRIPTION
**Pull request by smurphy8**
Created data-utilities dropped sandbox

Dropped files in sandbox

Added codepen

### CODE REVIEW

**Comment by smurphy8** [comment]
For some reason when I do a pull from upstream it isn't showing any missing stuff but then when I look here it says merging is blocked.

**Review by thirdcreed — APPROVED** [review]
This all seems pretty straightforward.  I don't know that it's necessary to keep archived, and deprecated folders around.  IMO that's what version control is for.   We could always go to an old commit if we wanted to find old code

**Comment by smurphy8** [comment]
Fair point

**Comment by smurphy8** [comment]
Is this holding for any reason?

**Comment by jagthedrummer** [comment]
@smurphy8 Is there any background on this one? I guess I didn't realize we were ditching the sandbox, and just want to make sure that everyone is cool with that. Any thoughts on this @mascott and @mkchandler?

**Comment by smurphy8** [comment]
Issue number 79 outlays my case for it... everyone seemed on board

**Comment by jagthedrummer** [comment]
@smurphy8, maybe I'm missing something, but this thread _is_ issue #79, and I'm not finding any discussion about the _why_.

**Comment by smurphy8** [comment]
@jagthedrummer it would be helpful if I could write the right issue numbers down goodness...
https://github.com/codeforokc/openbudgetokc/issues/78

**Comment by mkchandler** [comment]
I'm good with this for the reasons outlined in #78. @jagthedrummer do you have any objections?

**Pull request merged**
